---
name: Development Environment
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/devenv.yml'
      - 'devenv/**'
  pull_request:
    paths:
      - '.github/workflows/devenv.yml'
      - 'devenv/**'
  workflow_dispatch:
jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine if we should push changes and which tags to use
        if: github.event_name == 'workflow_dispatch' || github.event.inputs.version == 'push'
        run: |
          echo "publish=true" >> $GITHUB_ENV
      - name: Determine if we should push changes and which tags to use
        if: github.event_name != 'workflow_dispatch' && github.event_name != 'push'
        run: |
          echo "publish=false" >> $GITHUB_ENV
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Hub Login
        if: github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ env.publish }}
          tags: netdata/devenv:latest
